#+TITLE: Org-lectures

#+begin_comment
Simplifying and automating the mundane task of creating, organizing, and finding
your static notes so that you can focus on their actual content. It does not
*alter* the way you would otherwise interact with your org files, like other
widely used packages.
#+end_comment


I'm keeping this sort because I do not feel like elaborating right now. I'll add
extensive documentation by the end of the week.

#+begin_src elisp
(use-package org-lectures
  :straight
  (:host github :repo "chatziiola/org-lectures")
  :config
  (setq org-lectures-dir (expand-file-name "/your/path"))
  (setq org-lectures-static-course-files-dir  "/your/path")
  (setq org-lectures-roam-id-integration  t)
  :general
  (lc/leader-keys
    "ll" '(org-lectures-find-course		:which-keys "lecture")
    "lF" '(org-lectures-dired-course-folder	:which-keys "Open course's folder"))
  )
#+end_src

* Quick Description:
This package allows the user to:
1. Easily organize and manage their lecture notes through an interactive prompt.
2. Easily navigate between lectures of the same course and their respective directories
3. 

* Tips
Check out the ~cdlatex~ package, especially if you are in a field with plenty of mathematics. 
It allows for the smooth integration of latex inside of org mode.

* TODOs:
- [ ] Maybe implement classes. This is an obvious example of a program that
  could be improved with OOP.
  - https://www.gnu.org/software/emacs/manual/html_node/eieio/Building-Classes.html
- [ ] See ~org-lectures-find-course~ for improvement (quicker course creation)
- [ ] See maybe that you publish the /strange/ keyword library as well, because I
  do not like using it like that in various places
- [ ] See maybe that you publish the /strange/ keyword library as well, because
  I do not like using it like that in various places
